// ============================================================
// MBSI Library — Demo Data (Development Only)
// ============================================================

import type {
  User,
  Author,
  Category,
  Book,
  ReadingProgress,
  Bookmark,
  Favorite,
  Rating,
  RankingEntry,
} from "@/types";

// ─── Demo Users ─────────────────────────────────────────────
export const DEMO_USERS: User[] = [
  {
    id: "user-1",
    name: "Muhammadamin Toshtemirov",
    role: "STUDENT",
    avatar: "/avatars/student-1.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-2",
    name: "Aziz Karimov",
    role: "STUDENT",
    avatar: "/avatars/student-2.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-3",
    name: "Samir Rustamov",
    role: "STUDENT",
    avatar: "/avatars/student-3.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-4",
    name: "Nodira Abdullayeva",
    role: "STUDENT",
    avatar: "/avatars/student-4.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-5",
    name: "Jasur Toshmatov",
    role: "STUDENT",
    avatar: "/avatars/student-5.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-6",
    name: "Dilshod Mirzayev",
    role: "TEACHER",
    avatar: "/avatars/teacher-1.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-7",
    name: "Gulnora Karimova",
    role: "TEACHER",
    avatar: "/avatars/teacher-2.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "user-8",
    name: "Alisher Navoiy",
    role: "ADMIN",
    avatar: "/avatars/admin-1.svg",
    isActive: true,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
];

// ─── Demo Authors ───────────────────────────────────────────
export const DEMO_AUTHORS: Author[] = [
  {
    id: "author-1",
    name: "James Clear",
    biography: "American author and speaker known for his work on habits and decision-making.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-2",
    name: "Chingiz Aytmatov",
    biography: "Kyrgyz author who wrote in both Russian and Kyrgyz.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-3",
    name: "Abdulla Qodiriy",
    biography: "Uzbek writer, playwright, publicist. Author of 'O'tkan Kunlar'.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-4",
    name: "O'tkir Hoshimov",
    biography: "Uzbek writer, journalist, and playwright.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-5",
    name: "Stephen Hawking",
    biography: "British theoretical physicist and cosmologist.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-6",
    name: "Robin Sharma",
    biography: "Canadian lawyer and author of The Monk Who Sold His Ferrari.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-7",
    name: "Dale Carnegie",
    biography: "American writer and lecturer, developer of courses in self-improvement.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-8",
    name: "Norman Lewis",
    biography: "English linguist and author of vocabulary-building books.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-9",
    name: "Paulo Coelho",
    biography: "Brazilian lyricist and novelist, author of The Alchemist.",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "author-10",
    name: "Mehmon Baxtiyorov",
    biography: "Uzbek educator and methodologist.",
    createdAt: "2025-09-01T00:00:00Z",
  },
];

// ─── Demo Categories ────────────────────────────────────────
export const DEMO_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Ommabop ilm-fan",
    slug: "ommabop-ilm-fan",
    description: "Ilmiy kitoblar oddiy tilda",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-2",
    name: "Badiiy adabiyot",
    slug: "badiiy-adabiyot",
    description: "Roman, hikoya, poemalar",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-3",
    name: "O'zbek adabiyoti",
    slug: "ozbek-adabiyoti",
    description: "Milliy adabiyot namunalari",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-4",
    name: "Fizika",
    slug: "fizika",
    description: "Fizika faniga oid kitoblar",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-5",
    name: "Matematika",
    slug: "matematika",
    description: "Matematika faniga oid kitoblar",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-6",
    name: "Ingliz tili",
    slug: "ingliz-tili",
    description: "Ingliz tili o'rganish kitoblari",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-7",
    name: "Shaxsiy rivojlanish",
    slug: "shaxsiy-rivojlanish",
    description: "O'zini rivojlantirish kitoblari",
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "cat-8",
    name: "Tarix",
    slug: "tarix",
    description: "Tarixiy kitoblar",
    createdAt: "2025-09-01T00:00:00Z",
  },
];

// ─── Demo Books ─────────────────────────────────────────────
export const DEMO_BOOKS: Book[] = [
  {
    id: "book-1",
    title: "Atomic Habits",
    description:
      "Atomic Habits by James Clear is a revolutionary book that teaches you how to build good habits and break bad ones. The book explains how habits shape your identity and how you can use the Four Laws of Behavior Change to build better habits that stick.",
    coverUrl: "/covers/atomic-habits.svg",
    pdfUrl: "pdfs/book-1.pdf",
    language: "EN",
    totalPages: 15,
    authorId: "author-1",
    categoryId: "cat-7",
    isPublished: true,
    averageRating: 4.7,
    totalReaders: 156,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-2",
    title: "O'tkan Kunlar",
    description:
      "Abdulla Qodiriyning 'O'tkan Kunlar' romani o'zbek adabiyotining eng mashhur asarlaridan biri. U 1920-yillardagi O'zbekiston hayotini aks ettiradi.",
    coverUrl: "/covers/otkan-kunlar.svg",
    pdfUrl: "/books/otkan-kunlar.pdf",
    language: "UZ",
    totalPages: 280,
    authorId: "author-3",
    categoryId: "cat-3",
    isPublished: true,
    averageRating: 4.8,
    totalReaders: 234,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-3",
    title: "Fizika 9-sinf",
    description:
      "O'zbekiston Respublikasi oliy ta'lim, fan va innovatsiyalar vazirligi tomonidan tasdiqlangan darslik.",
    coverUrl: "/covers/fizika-9.svg",
    pdfUrl: "/books/fizika-9.pdf",
    language: "UZ",
    totalPages: 240,
    authorId: "author-10",
    categoryId: "cat-4",
    isPublished: true,
    averageRating: 4.2,
    totalReaders: 312,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-4",
    title: "Jismoniy tarbiya 8-sinf",
    description:
      "Maktablarda jismoniy tarbiya fani uchun darslik.",
    coverUrl: "/covers/jismoniy-tarbiya.svg",
    pdfUrl: "/books/jismoniy-tarbiya.pdf",
    language: "UZ",
    totalPages: 180,
    authorId: "author-10",
    categoryId: "cat-4",
    isPublished: true,
    averageRating: 4.0,
    totalReaders: 189,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-5",
    title: "A Brief History of Time",
    description:
      "Stephen Hawking's bestselling book explains complex cosmological concepts to the general reader, covering topics from the Big Bang to black holes.",
    coverUrl: "/covers/brief-history.svg",
    pdfUrl: "/books/brief-history.pdf",
    language: "EN",
    totalPages: 256,
    authorId: "author-5",
    categoryId: "cat-1",
    isPublished: true,
    averageRating: 4.6,
    totalReaders: 178,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-6",
    title: "The Monk Who Sold His Ferrari",
    description:
      "A fable about fulfilling your dreams and reaching your destiny. Robin Sharma tells the story of a lawyer who gives up everything to find true happiness.",
    coverUrl: "/covers/monk-ferrari.svg",
    pdfUrl: "/books/monk-ferrari.pdf",
    language: "EN",
    totalPages: 198,
    authorId: "author-6",
    categoryId: "cat-7",
    isPublished: true,
    averageRating: 4.5,
    totalReaders: 145,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-7",
    title: "How to Win Friends and Influence People",
    description:
      "Dale Carnegie's timeless guide to interpersonal relationships, communication, and leadership skills.",
    coverUrl: "/covers/win-friends.svg",
    pdfUrl: "/books/win-friends.pdf",
    language: "EN",
    totalPages: 288,
    authorId: "author-7",
    categoryId: "cat-7",
    isPublished: true,
    averageRating: 4.4,
    totalReaders: 203,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-8",
    title: "Word Power Made Easy",
    description:
      "Norman Lewis's classic vocabulary builder that has helped millions improve their English vocabulary and communication skills.",
    coverUrl: "/covers/word-power.svg",
    pdfUrl: "/books/word-power.pdf",
    language: "EN",
    totalPages: 352,
    authorId: "author-8",
    categoryId: "cat-6",
    isPublished: true,
    averageRating: 4.3,
    totalReaders: 167,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-9",
    title: "The Alchemist",
    description:
      "Paulo Coelho's masterpiece tells the story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
    coverUrl: "/covers/alchemist.svg",
    pdfUrl: "/books/alchemist.pdf",
    language: "EN",
    totalPages: 208,
    authorId: "author-9",
    categoryId: "cat-2",
    isPublished: true,
    averageRating: 4.6,
    totalReaders: 198,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-10",
    title: "Matematika 7-sinf",
    description:
      "O'zbekiston maktablari uchun matematika darslik.",
    coverUrl: "/covers/matematika-7.svg",
    pdfUrl: "/books/matematika-7.pdf",
    language: "UZ",
    totalPages: 220,
    authorId: "author-10",
    categoryId: "cat-5",
    isPublished: true,
    averageRating: 4.1,
    totalReaders: 287,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-11",
    title: "Jannatda Ikki Boshli Qush",
    description:
      "Chingiz Aytmatovning mashhur asari. Qadimiy urf-odatlar va zamonaviy hayot o'rtasidagi ziddiyat haqida.",
    coverUrl: "/covers/jannatda-qush.svg",
    pdfUrl: "/books/jannatda-qush.pdf",
    language: "UZ",
    totalPages: 150,
    authorId: "author-2",
    categoryId: "cat-2",
    isPublished: true,
    averageRating: 4.7,
    totalReaders: 165,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-12",
    title: "Dunyoning Ishlari",
    description:
      "O'tkir Hoshimovning 'Dunyoning Ishlari' romani — o'zbek adabiyotining yorqin namunasi.",
    coverUrl: "/covers/dunyoning-ishlari.svg",
    pdfUrl: "/books/dunyoning-ishlari.pdf",
    language: "UZ",
    totalPages: 290,
    authorId: "author-4",
    categoryId: "cat-3",
    isPublished: true,
    averageRating: 4.5,
    totalReaders: 189,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-13",
    title: "Fizika 8-sinf",
    description:
      "O'zbekiston Respublikasi oliy ta'lim, fan va innovatsiyalar vazirligi tomonidan tasdiqlangan 8-sinf fizika darsligi.",
    coverUrl: "/covers/fizika-8.svg",
    pdfUrl: "/books/fizika-8.pdf",
    language: "UZ",
    totalPages: 210,
    authorId: "author-10",
    categoryId: "cat-4",
    isPublished: true,
    averageRating: 4.3,
    totalReaders: 256,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-14",
    title: "Matematika 9-sinf",
    description:
      "O'zbekiston maktablari uchun 9-sinf matematika darslik.",
    coverUrl: "/covers/matematika-9.svg",
    pdfUrl: "/books/matematika-9.pdf",
    language: "UZ",
    totalPages: 260,
    authorId: "author-10",
    categoryId: "cat-5",
    isPublished: true,
    averageRating: 4.0,
    totalReaders: 234,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-15",
    title: "Ingliz tili 5-sinf",
    description:
      "Maktablarda ingliz tili fani uchun darslik.",
    coverUrl: "/covers/ingliz-tili-5.svg",
    pdfUrl: "/books/ingliz-tili-5.pdf",
    language: "UZ",
    totalPages: 140,
    authorId: "author-10",
    categoryId: "cat-6",
    isPublished: true,
    averageRating: 4.2,
    totalReaders: 345,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-16",
    title: "Deep Work",
    description:
      "Cal Newport explores how focused work can lead to professional success and personal fulfillment in an increasingly distracted world.",
    coverUrl: "/covers/deep-work.svg",
    pdfUrl: "/books/deep-work.pdf",
    language: "EN",
    totalPages: 296,
    authorId: "author-6",
    categoryId: "cat-7",
    isPublished: true,
    averageRating: 4.4,
    totalReaders: 132,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-17",
    title: "O'zbekiston Tarixi",
    description:
      "O'zbekistonning boy tarixi haqida batafsil kitob.",
    coverUrl: "/covers/ozbek-tarixi.svg",
    pdfUrl: "/books/ozbek-tarixi.pdf",
    language: "UZ",
    totalPages: 340,
    authorId: "author-10",
    categoryId: "cat-8",
    isPublished: true,
    averageRating: 4.3,
    totalReaders: 178,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-18",
    title: "Think and Grow Rich",
    description:
      "Napoleon Hill's classic personal development and self-help book that has helped millions achieve financial success.",
    coverUrl: "/covers/think-grow-rich.svg",
    pdfUrl: "/books/think-grow-rich.pdf",
    language: "EN",
    totalPages: 320,
    authorId: "author-7",
    categoryId: "cat-7",
    isPublished: true,
    averageRating: 4.5,
    totalReaders: 156,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-19",
    title: "Rus tili 6-sinf",
    description:
      "Maktablarda rus tili fani uchun darslik.",
    coverUrl: "/covers/rus-tili-6.svg",
    pdfUrl: "/books/rus-tili-6.pdf",
    language: "RU",
    totalPages: 170,
    authorId: "author-10",
    categoryId: "cat-6",
    isPublished: true,
    averageRating: 4.1,
    totalReaders: 198,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "book-20",
    title: "Biologiya 7-sinf",
    description:
      "O'zbekiston maktablari uchun biologiya darslik.",
    coverUrl: "/covers/biologiya-7.svg",
    pdfUrl: "/books/biologiya-7.pdf",
    language: "UZ",
    totalPages: 190,
    authorId: "author-10",
    categoryId: "cat-1",
    isPublished: true,
    averageRating: 4.2,
    totalReaders: 267,
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
];

// ─── Demo Reading Progress ──────────────────────────────────
export const DEMO_READING_PROGRESS: ReadingProgress[] = [
  {
    id: "rp-1",
    userId: "user-1",
    bookId: "book-1",
    currentPage: 118,
    totalPages: 320,
    progress: 37,
    startedAt: "2025-09-10T08:00:00Z",
    lastReadAt: "2025-09-20T14:30:00Z",
  },
  {
    id: "rp-2",
    userId: "user-1",
    bookId: "book-2",
    currentPage: 179,
    totalPages: 280,
    progress: 64,
    startedAt: "2025-09-05T10:00:00Z",
    lastReadAt: "2025-09-19T16:00:00Z",
  },
  {
    id: "rp-3",
    userId: "user-1",
    bookId: "book-3",
    currentPage: 50,
    totalPages: 240,
    progress: 21,
    startedAt: "2025-09-15T09:00:00Z",
    lastReadAt: "2025-09-18T11:00:00Z",
  },
  {
    id: "rp-4",
    userId: "user-2",
    bookId: "book-1",
    currentPage: 240,
    totalPages: 320,
    progress: 75,
    startedAt: "2025-09-08T12:00:00Z",
    lastReadAt: "2025-09-20T18:00:00Z",
  },
  {
    id: "rp-5",
    userId: "user-3",
    bookId: "book-9",
    currentPage: 208,
    totalPages: 208,
    progress: 100,
    startedAt: "2025-09-01T10:00:00Z",
    lastReadAt: "2025-09-15T20:00:00Z",
    completedAt: "2025-09-15T20:00:00Z",
  },
];

// ─── Demo Bookmarks ─────────────────────────────────────────
export const DEMO_BOOKMARKS: Bookmark[] = [
  {
    id: "bm-1",
    userId: "user-1",
    bookId: "book-1",
    page: 50,
    createdAt: "2025-09-12T10:00:00Z",
  },
  {
    id: "bm-2",
    userId: "user-1",
    bookId: "book-1",
    page: 100,
    createdAt: "2025-09-15T14:00:00Z",
  },
  {
    id: "bm-3",
    userId: "user-1",
    bookId: "book-2",
    page: 45,
    createdAt: "2025-09-08T09:00:00Z",
  },
];

// ─── Demo Favorites ─────────────────────────────────────────
export const DEMO_FAVORITES: Favorite[] = [
  {
    id: "fav-1",
    userId: "user-1",
    bookId: "book-1",
    createdAt: "2025-09-10T08:00:00Z",
  },
  {
    id: "fav-2",
    userId: "user-1",
    bookId: "book-2",
    createdAt: "2025-09-05T10:00:00Z",
  },
  {
    id: "fav-3",
    userId: "user-2",
    bookId: "book-9",
    createdAt: "2025-09-08T12:00:00Z",
  },
];

// ─── Demo Ratings ───────────────────────────────────────────
export const DEMO_RATINGS: Rating[] = [
  {
    id: "r-1",
    userId: "user-1",
    bookId: "book-1",
    rating: 5,
    createdAt: "2025-09-15T14:00:00Z",
    updatedAt: "2025-09-15T14:00:00Z",
  },
  {
    id: "r-2",
    userId: "user-1",
    bookId: "book-2",
    rating: 5,
    createdAt: "2025-09-10T12:00:00Z",
    updatedAt: "2025-09-10T12:00:00Z",
  },
  {
    id: "r-3",
    userId: "user-2",
    bookId: "book-1",
    rating: 4,
    createdAt: "2025-09-12T10:00:00Z",
    updatedAt: "2025-09-12T10:00:00Z",
  },
  {
    id: "r-4",
    userId: "user-3",
    bookId: "book-9",
    rating: 5,
    createdAt: "2025-09-14T16:00:00Z",
    updatedAt: "2025-09-14T16:00:00Z",
  },
];

// ─── Demo Rankings ──────────────────────────────────────────
export const DEMO_RANKINGS: RankingEntry[] = [
  { rank: 1, userId: "user-1", totalPages: 12840, totalBooks: 45, readingTime: 1820, streak: 12 },
  { rank: 2, userId: "user-2", totalPages: 10420, totalBooks: 38, readingTime: 1560, streak: 8 },
  { rank: 3, userId: "user-3", totalPages: 9870, totalBooks: 35, readingTime: 1420, streak: 15 },
  { rank: 4, userId: "user-4", totalPages: 8650, totalBooks: 30, readingTime: 1280, streak: 5 },
  { rank: 5, userId: "user-5", totalPages: 7890, totalBooks: 28, readingTime: 1150, streak: 10 },
  { rank: 6, userId: "user-6", totalPages: 6540, totalBooks: 22, readingTime: 980, streak: 3 },
  { rank: 7, userId: "user-7", totalPages: 5320, totalBooks: 18, readingTime: 780, streak: 7 },
];
